Resources:
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: ./code
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.8
      MemorySize: 512
      Timeout: 900
      Handler: main.handler

  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
